### ISSUE TITLE
MySQL problem dial cloudsql: unknown network cloudsql

### ISSUE THREAD

**Issue by camstuart** [GoogleCloudPlatform/golang-samples#692]
Hi,

In GAE Standard Go 1.11, I am not able to connect to cloud SQL.

The error I get is:

```
dial cloudsql: unknown network cloudsql
```

I am definitely using the correct DSN as an env var in `app.yaml`:

```
runtime: go111

service: myservice

env_variables:
  DSN: "user:pass@cloudsql(canwork-io:australia-southeast1:canwork-io)/db_name?parseTime=true"

handlers:
- url: /.*
  script: auto
```

I tried changing to `tcp` and also tried using the IP address, but still no luck
