### ISSUE TITLE
Deploying Go app to GAE standard environment with TravisCI

### ISSUE THREAD

**Issue by forstmeier** [GoogleCloudPlatform/golang-samples#930]
### Description
I'm in the process of configuring my Go app to be able to be automatically deployed to GAE in the standard environment on pushes to `master` on GitHub.

So far, I've been able to set it up using Google App Engine's flexible environment but I'm unable to take advantage of the Free Tier by doing so. I'm pretty sure what I'm doing wrong is misconfiguring my `cloudbuild.yml` file since it _seems_ like the code is actually getting to GAE but it will not run when it gets there.

Here's my `app.yaml`:
```yaml
runtime: go112
```

Here's my `cloudbuild.yaml`:
```yaml
steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['install', '.']
    env: ['PROJECT_ROOT=watchmyrepo']
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', 'watchmyrepo']
    env: ['PROJECT_ROOT=watchmyrepo']
  - name: 'gcr.io/cloud-builders/go'
    args: ['run', 'watchmyrepo']
    env: ['PROJECT_ROOT=watchmyrepo']
  artifacts:
    objects:
      location: 'gs://watchmyrepo-248001/'
      paths: ['watchmyrepo']
```

The Go app itself is relatively standard in its layout/design and can be found [here where I'm working on the "gae-standard" branch](https://github.com/forstmeier/watchmyrepo/tree/gae-standard).

I'd ideally love to have:
- TravisCI run tests/deploy code to GAE
- GAE running the code in the standard environment

Right now, the TravisCI output _seems_ like it's deploying successfully, based on the logs (see below) and I see the project getting updated in the GCP console (see below again) but there are no running instances - I feel like I'm missing something super simple but can't quite figure out what it is.

<img width="824" alt="Screen Shot 2019-08-01 at 7 59 21 PM" src="https://user-images.githubusercontent.com/13358530/62334884-70f9ef00-b497-11e9-9314-6e935ac3c208.png">

<img width="1493" alt="Screen Shot 2019-08-01 at 8 04 17 PM" src="https://user-images.githubusercontent.com/13358530/62334935-ad2d4f80-b497-11e9-91ba-ba0b65be0a12.png">

If anyone has a good example to point me at, or some insight into what I'm doing wrong, I'd appreciate it.
